[package]
name = "mcdp-tool"
version = "0.4.0"
edition = "2024"
authors = ["Your Name <your.email@example.com>"]
description = "CLI tool with self-update capability"
readme = "README.md"
repository = "https://github.com/zupermind/mcdp-binaries"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive", "help", "std", "color", "usage", "error-context", "suggestions"], default-features = false }
env_logger = { version = "0.11", default-features = false }
log = { version = "0.4", default-features = false }
self_update = { version = "0.38", features = ["archive-tar", "compression-flate2", "rustls"], default-features = false }

zuper-rs-cbor-utils = { version = "7", registry = "zuper-registry" }
 
[[bin]]
path = "src/main.rs"
name = "mcdp-tool"
required-features = []
