[package]
name = "mcdp-tool"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "CLI tool with self-update capability"
repository = "https://github.com/zupermind/mcdp-binaries"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
self_update = { version = "0.42", features = ["archive-tar", "compression-flate2", "rustls"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"